#!/bin/sh
set -e
echo 'Installing python3 dependencies...'
pip3 install -r /usr/share/stoneaggregator/requirements.txt
echo 'Setting up service...'
systemctl enable --now stoneaggregator.service || true
